Basics of Nump

In [3]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b=np.array([[1.2,5.4],[3.5,7.04]])
print(b)

[[1.2  5.4 ]
 [3.5  7.04]]


Array atributes

In [13]:
a.dtype
a.size
a.shape
a.ndim

1

Sorting

In [14]:
arr=np.array([3,5,2,17,8,4,9,10])
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 10, 17])

Concatenate

In [16]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

Reshape

In [17]:
a=np.array([1,2,3,4,5,6,7,8,9])
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Indexing and slicing

In [29]:
data = np.array([1, 2, 3,4,5,6,7,8,9])
a=data.copy()
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Basic array operations

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a*b
a+a
a.sum()
b.sum()
c=np.array([[1,1,1],[2,3,4]])
c.sum(axis=0)

array([3, 4, 5])

: 

In [27]:
a=np.array([1,2,3,4,5])
b=np.array([5,4,3,2,1])
a * b

array([5, 8, 9, 8, 5])

In [18]:
a.sum()
a.prod()

arr = np.array([[3,7,1],[2,8,5,],[4,9,6]])

arr.max(axis=1)

array([7, 8, 9])

In [19]:
arr[1,1]

8

In [29]:
#Random number
rng = np.random.default_rng()
a=rng.integers(10,size=(3,3))
a

array([[4, 4, 8],
       [6, 1, 3],
       [7, 6, 2]], dtype=int64)

In [ ]:
#Get unique values and count
np.unique(a,return_index=True,return_counts=True)

In [ ]:
a=np.arange(6)
a
a=a.reshape(2,3)
a=a.T
a

In [ ]:
#How to reverse an array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

r = np.flip(arr)
r

In [ ]:
# How to reverse a 2d array

arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

r=np.flip(arr_2d[2])

r

In [ ]:
#Flatten or ravel
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b= a.flatten()
print(a)
b[2]=111
print(a)
b

In [ ]:
arr=rng.integers(101,size=(10,10),dtype=int)

np.savetxt('new_file.csv', arr)

In [54]:
np.loadtxt('new_file.csv')

array([[39., 31., 50., 41., 97., 38., 74., 10., 28., 37.],
       [43., 45., 44., 27.,  3., 63., 32., 53., 59., 73.],
       [39., 51.,  9., 30., 74., 61., 21., 40., 89., 35.],
       [18., 65., 17., 44., 85., 63., 59., 43., 94., 99.],
       [60., 53., 27., 21., 19., 38., 64., 98., 20., 68.],
       [59., 32.,  0., 84., 40., 33., 17., 37., 98., 30.],
       [ 4.,  2., 43., 46., 71., 95., 81., 58., 58., 67.],
       [33., 71., 81., 91., 58., 52., 36., 28., 39., 67.],
       [59., 56., 55., 14., 23., 32., 78., 39., 87., 82.],
       [49., 82., 68., 66.,  8., 13., 90., 25., 32., 96.]])